version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:774305595347:task-definition/blacklist-task-definition:19"
        LoadBalancerInfo:
          ContainerName: "blacklist-api"
          ContainerPort: 5000

Hooks:
  BeforeInstall:
    - location: force_fail.sh
      timeout: 60
      runas: root

TrafficRouting:
  Type: AllAtOnce